DEFAULT_CONFIG = {
    "check_interval_seconds": 15,
    "request_timeout_ms": 3000,
}

ALERT_THRESHOLD = 0.20
MAX_HISTORY = 1000
MAX_MONITOR_CONCURRENCY = 50
MONITOR_STUCK_TIMEOUT_SECONDS = 60
MIN_FRESH_CHECK_GAP_SECONDS = 0.25

DEFAULT_EVENTS = ["alert.fired", "alert.resolved"]
SUPPORTED_INTEGRATIONS = {"slack", "discord"}

WEBHOOK_QUEUE_SIZE = 100
WEBHOOK_MAX_DELIVERY_SECONDS = 58
WEBHOOK_PER_ATTEMPT_TIMEOUT_SECONDS = 10
WEBHOOK_RETRY_DELAYS_SECONDS = [0.5, 1, 2, 4, 8, 8]
WEBHOOK_TRANSIENT_STATUS_CODES = {500, 502, 503, 504}
WEBHOOK_MAX_REDIRECTS = 5
